<a href="https://colab.research.google.com/github/ArnavM2008/ba-ai-project/blob/main/week2_sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import pandas as pd, sqlite3
df = pd.read_csv("https://raw.githubusercontent.com/ArnavM2008/ba-ai-project/refs/heads/main/Brazilian_Cup_Matches.csv")
df = df.drop_duplicates().dropna()
df.columns = (df.columns.str.strip()
.str.lower().str.replace(" ", "_"))

In [31]:
conn = sqlite3.connect(":memory:")
df.to_sql("data", conn, index=False)
def q(sql): return pd.read_sql(sql, conn)

In [32]:
q("SELECT * FROM data LIMIT 5")

,round,datetime,home_team,away_team,home_goal,away_goal,season
0,1,2012-03-07 16:00:00,Boavista Sport Club (antigo Esporte Clube Barr...,América - MG,0.0,0.0,2012
1,1,2012-03-14 20:30:00,América - MG,Boavista Sport Club (antigo Esporte Clube Barr...,2.0,1.0,2012
2,1,2012-03-07 19:30:00,Gama - DF,Ceará - CE,0.0,2.0,2012
3,1,2012-03-07 20:30:00,Aquidauanense Futebol Clube - MS,Bahia de Feira - BA,1.0,0.0,2012
4,1,2012-03-14 20:30:00,Bahia de Feira - BA,Aquidauanense Futebol Clube - MS,2.0,0.0,2012

In [33]:
q("SELECT COUNT(*) FROM data")

   COUNT(*)
0      1321

In [34]:
df.dtypes

round          int64
datetime      object
home_team     object
away_team     object
home_goal    float64
away_goal    float64
season         int64
dtype: object

1. My table has 1,321 rows
2. One row = one match
3. Numbers to add up: home_goal, away_goal
4. Groups to compare: home_team, away_team, season, round

How many matches did the home team win?

In [35]:
q("""
SELECT COUNT(*) AS orders
FROM data
WHERE season = '2021'
""")

   orders
0      92

In [36]:
q("""
SELECT COUNT(*) AS orders
FROM data
WHERE home_goal > 2
""")

   orders
0     211

In [37]:
q("""
SELECT home_team,
COUNT(*) AS total
FROM data
GROUP BY home_team
""")

                 home_team  total
0          4 de Julho - PI      3
1       7 de Setembro - MS      1
2              A.b.c. - RN      1
3              A.s.a. - AL      6
4                 ABC - RN      2
..                     ...    ...
270   Votuporanguense - SP      1
271  Xv de Piracicaba - SP      2
272          Ypiranga - AP      2
273          Ypiranga - RS      3
274       Águia Negra - MS      3

[275 rows x 2 columns]

In [38]:
q("""
SELECT home_team,
COUNT(*) AS total
FROM data
GROUP BY home_team
ORDER BY total ASC
LIMIT 5
""")

            home_team  total
0  7 de Setembro - MS      1
1         A.b.c. - RN      1
2          Aguia - PA      1
3    Aguia Negra - MS      1
4         Aimoré - RS      1

Q1 - How many matches had 4 or more goals?

home_goal, away_goal

Q2 - Which season had the most ties in matches?

season, home_goal, away_goal

Q3 - What are the top 5 home teams that had the highest total goals in a specific season?

home_team, home_goals, away_goals, season

In [39]:
df.columns

Index(['round', 'datetime', 'home_team', 'away_team', 'home_goal', 'away_goal',
       'season'],
      dtype='object')

In [40]:
q("""
SELECT COUNT(*) AS orders
FROM data
WHERE home_goal + away_goal >= 4
""")

   orders
0     278

278 matches had 4 or more total goals.

In [49]:
q("""
SELECT season, COUNT(*) AS ties
FROM data
WHERE home_goal = away_goal
GROUP BY season
ORDER BY ties DESC
LIMIT 1
""")

   season  ties
0    2016    50

The 2016 season had the most ties with 50 ties.

In [50]:
q("""
SELECT home_team, SUM(home_goal) AS total_goals
FROM data
WHERE season = 2020
GROUP BY home_team
ORDER BY total_goals DESC
LIMIT 5
""")

          home_team  total_goals
0        Ceará - CE          9.0
1  Ferroviária - SP          8.0
2      Brusque - SC          8.0
3    Palmeiras - SP          7.0
4     Atlético - GO          7.0

During season 2020, the top 5 home teams scoring the most goals were Ceará, Ferroviária, Brusque, Palmeiras, and Atlético