In [9]:
import pandas as pd, sqlite3
df = pd.read_csv("https://raw.githubusercontent.com/ArnavM2008/ba-ai-project/refs/heads/main/Brazilian_Cup_Matches.csv")
df = df.drop_duplicates().dropna()
df.columns = (df.columns.str.strip()
.str.lower().str.replace(" ", "_"))

In [3]:
conn = sqlite3.connect(":memory:")
df.to_sql("data", conn, index=False)
def q(sql): return pd.read_sql(sql, conn)

In [4]:
q("SELECT * FROM data LIMIT 5")

,round,datetime,home_team,away_team,home_goal,away_goal,season
0,1,2012-03-07 16:00:00,Boavista Sport Club (antigo Esporte Clube Barr...,América - MG,0.0,0.0,2012
1,1,2012-03-14 20:30:00,América - MG,Boavista Sport Club (antigo Esporte Clube Barr...,2.0,1.0,2012
2,1,2012-03-07 19:30:00,Gama - DF,Ceará - CE,0.0,2.0,2012
3,1,2012-03-07 20:30:00,Aquidauanense Futebol Clube - MS,Bahia de Feira - BA,1.0,0.0,2012
4,1,2012-03-14 20:30:00,Bahia de Feira - BA,Aquidauanense Futebol Clube - MS,2.0,0.0,2012

In [5]:
q("SELECT COUNT(*) FROM data")

   COUNT(*)
0      1321

In [ ]:
df.dtypes

round          int64
datetime      object
home_team     object
away_team     object
home_goal    float64
away_goal    float64
season         int64
dtype: object

1. My table has 1,321 rows
2. One row = one match
3. Numbers to add up: home_goal, away_goal
4. Groups to compare: home_team, away_team, season, round

In [ ]:
q("""
SELECT home_team,
COUNT(*) AS total
FROM data
GROUP BY home_team
""")

                 home_team  total
0          4 de Julho - PI      3
1       7 de Setembro - MS      1
2              A.b.c. - RN      1
3              A.s.a. - AL      6
4                 ABC - RN      2
..                     ...    ...
270   Votuporanguense - SP      1
271  Xv de Piracicaba - SP      2
272          Ypiranga - AP      2
273          Ypiranga - RS      3
274       Águia Negra - MS      3

[275 rows x 2 columns]

Q1 - How many matches did the home team win?

home_goal, away_goal

Q2 - Which season had the greatest average difference between home goals and away goals?

season, home_goal, away_goal

Q3 - What are the top 5 home teams that had the highest total goals difference between home and away goals in 2020?

home_team, home_goal, away_goal, season

In [ ]:
df.columns

Index(['round', 'datetime', 'home_team', 'away_team', 'home_goal', 'away_goal',
       'season'],
      dtype='object')

In [6]:
q("""
SELECT COUNT(*) AS home_wins
FROM data
WHERE home_goal > away_goal
""")

   home_wins
0        579



The home team won 579 matches.

In [10]:
q("""
SELECT season, AVG(home_goal - away_goal) AS avg_goal_difference
FROM data
GROUP BY season
ORDER BY avg_goal_difference DESC
""")

   season  avg_goal_difference
0    2014             0.496855
1    2012             0.473214
2    2016             0.395062
3    2013             0.367089
4    2015             0.335443
5    2019             0.233333
6    2017             0.216667
7    2020             0.191667
8    2018             0.141667
9    2021            -0.326087

The 2014 season had the greatest average home away goal difference with .497 goals per match.

In [8]:
q("""
SELECT home_team, SUM(home_goal - away_goal) AS total_goal_difference
FROM data
WHERE season = 2020
GROUP BY home_team
ORDER BY total_goal_difference DESC
LIMIT 5
""")

          home_team  total_goal_difference
0    Palmeiras - SP                    6.0
1   Fluminense - RJ                    6.0
2  Ferroviária - SP                    6.0
3        Ceará - CE                    6.0
4      Brusque - SC                    4.0

During season 2020, Palmeiras - SP had the highest total home to away goal difference of 6, followed by Fluminense - RJ, Ferroviária, and Ceará with differences of 6 goals each, and Brusque with 4.